# Generated by Django 2.1.7 on 2019-03-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_auto_20190322_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Publicado'),
        ),
    ]
