# Generated by Django 2.1.7 on 2019-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20190322_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(verbose_name='Conteudo'),
        ),
    ]
